### ISSUE TITLE
Ajude a traduzir o material em inglês do repositório original

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/como-contribuir-com-codigo-aberto#2]
Ajude a traduzir os arquivos `README_pt-br.md` e `PROJECTS_pt-br.md`.

**Comment by joncasdam** [comment]
O `README_pt-br.md` parece já estar traduzido.

**Comment by gustafsilva** [comment]
Olá @joncasdam , o `README.md` já está sim porém o `CONTRIBUTING.md` está todo em inglês...
Poderia trabalhar nele?
Seria legal criar um arquivo `CONTRIBUTING_pt-br.md` :smile:
