### ISSUE TITLE
Ajustar links no arquivo README_pt-br.md

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/como-contribuir-com-codigo-aberto#3]
Ajustar links na documentação em português (README_pt-br.md) na seção de `Índice`.

**Comment by kelvinromero** [comment]
Oi, eu gostaria de ajudar nessa Issue. No caso seria só traduzir tudo para português. E qual o padrão correto? Como do projeto Babel ou como o do freeCodeCamp?

**Comment by gustafsilva** [comment]
Seria ótimo @kelvinromero ! :smile: 
Pensei em verificar se tem o mesmo material dos links (que está em inglês) mas em português...
Encontrei alguns e já modifiquei (como os livros :book:) no arquivo `README_pt-br.md`.
Você poderia fazer isso? :laughing:

**Comment by kelvinromero** [comment]
Posso sim, começando agora!

**Comment by kelvinromero** [comment]
Só um dos links tinha uma versão disponível em português. Uma possibilidade seria buscar "equivalentes" em português, e subdivir os links entre os já disponíveis e em português.

**Comment by gustafsilva** [comment]
> Só um dos links tinha uma versão disponível em português. Uma possibilidade seria buscar "equivalentes" em português, e subdivir os links entre os já disponíveis e em português.

Ótimo @kelvinromero , irei criar uma nova `issue` para esta tarefa... :hammer:
Muito obrigado pela sua contribuição... :+1: 
Feliz Hacktoberfest! :smile:
